### ISSUE TITLE
Dragging appears limited

### ISSUE THREAD

**Issue by nickkie009** [deatul/vSort#1]
This is a useful utility by design, but in operation I'm finding if the list is longer than the screen is capable of displaying it fails to perform. Dragging above the top of the screen or below the screen fails to scroll the display.  The result is only the elements shown on the screen can be reordered by dragging.

**Comment by lastdates** [comment]
I am aware of the issue, and current practical alternative is to restrict the height of item along with overflow:auto; to show inline scroll bar.
Will look into ways to patch this issue soon.

**Comment by nickkie009** [comment]
That would be great.  It should be stated that a vSort list can contain nested lists and I find that particularly useful.  Thanks!
